version: "3.7"

services:
  vscode:
    image: qmcgaw/reactdevcontainer
    volumes:
      - node_modules:/workspace/node_modules
      - ../:/workspace
      - ~/.ssh:/home/vscode/.ssh:ro
      - ~/.ssh:/root/.ssh:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - TZ=
    entrypoint: zsh -c "while sleep 1000; do :; done"
    ports:
      - 3000/tcp

volumes:
  node_modules:
